# Generated by Django 5.2.5 on 2025-09-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0002_remove_customer_customer_id_remove_order_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='display_item',
            field=models.BooleanField(default=True),
        ),
    ]
